---
- name: Add net.ifnames=0 to /boot/cmdline.txt for classic interface naming
  ansible.builtin.replace:
    path: /boot/cmdline.txt
    regexp: '(?<!net\.ifnames=0 )rootwait'
    replace: 'net.ifnames=0 rootwait'

- name: Unmask and enable dhcpcd service
  ansible.builtin.systemd:
    name: dhcpcd
    masked: false
    enabled: true
