- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Set default deny incoming
  community.general.ufw:
    default: deny
    direction: incoming
  become: true

- name: Set default allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing
  become: true

- name: Allow SSH (rate limited)
  community.general.ufw:
    rule: limit
    port: "22"
    proto: tcp
  become: true

- name: Allow all traffic from main workstation
  community.general.ufw:
    rule: allow
    from_ip: "{{ warrig_lan_ip }}"
  become: true

- name: Allow node_exporter from citadel
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "{{ citadel_lan_ip }}"
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true
