- name: Update apt cache (ignore errors from broken repos)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  failed_when: false
  when: ansible_facts['os_family'] == "Debian"

- name: Install node_exporter (Debian/Raspbian)
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install node_exporter (Archlinux)
  community.general.pacman:
    name: prometheus-node-exporter
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true
    daemon_reload: true
  become: true
