- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: true
  loop: "{{ package_list }}"
  become: true
